// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RC.MS_Divorcio.AccessData;

namespace RC.MS_Divorcio.AccessData.Migrations
{
    [DbContext(typeof(MS_DivorcioDbContext))]
    [Migration("20200517062614_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RC.MS_Divorcio.Domain.Entities.DetalleHijos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("DetalleHijos");
                });

            modelBuilder.Entity("RC.MS_Divorcio.Domain.Entities.DomicilioConvivencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("localidadId")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("provinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DomicilioConvivencia");
                });

            modelBuilder.Entity("RC.MS_Divorcio.Domain.Entities.Hijos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("detallehijosId")
                        .HasColumnType("int");

                    b.Property<int>("personaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("detallehijosId");

                    b.ToTable("Hijos");
                });

            modelBuilder.Entity("RC.MS_Divorcio.Domain.Entities.Propuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Propuestas");
                });

            modelBuilder.Entity("RC.MS_Divorcio.Domain.Entities.SolicitudTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SolicitudTipos");
                });

            modelBuilder.Entity("RC.MS_Divorcio.Domain.Entities.TramiteDivorcio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("actaMatrimonioId")
                        .HasColumnType("int");

                    b.Property<int>("detalleHijosId")
                        .HasColumnType("int");

                    b.Property<int>("domicilioConyugalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("personaId1")
                        .HasColumnType("int");

                    b.Property<int>("personaId2")
                        .HasColumnType("int");

                    b.Property<int>("propuestaId")
                        .HasColumnType("int");

                    b.Property<int?>("solicitudTipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("detalleHijosId");

                    b.HasIndex("domicilioConyugalId");

                    b.HasIndex("propuestaId");

                    b.HasIndex("solicitudTipoId");

                    b.ToTable("TramiteDivorcios");
                });

            modelBuilder.Entity("RC.MS_Divorcio.Domain.Entities.Hijos", b =>
                {
                    b.HasOne("RC.MS_Divorcio.Domain.Entities.DetalleHijos", null)
                        .WithMany("hijosNavigator")
                        .HasForeignKey("detallehijosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RC.MS_Divorcio.Domain.Entities.TramiteDivorcio", b =>
                {
                    b.HasOne("RC.MS_Divorcio.Domain.Entities.DetalleHijos", "detalleHijos")
                        .WithMany()
                        .HasForeignKey("detalleHijosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RC.MS_Divorcio.Domain.Entities.DomicilioConvivencia", "domicilioConyugal")
                        .WithMany()
                        .HasForeignKey("domicilioConyugalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RC.MS_Divorcio.Domain.Entities.Propuesta", "propuesta")
                        .WithMany()
                        .HasForeignKey("propuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RC.MS_Divorcio.Domain.Entities.SolicitudTipo", "solicitudTipo")
                        .WithMany()
                        .HasForeignKey("solicitudTipoId");
                });
#pragma warning restore 612, 618
        }
    }
}
